version: "3"

services:
  price-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Admin@Price.com

    # ports: 
    #   - '5432:5432'

  price-db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  pgdata: {}